### ISSUE TITLE
Linux sigma rules to kusto via microsoft xdr

### ISSUE THREAD

**Issue by KyootyBella** [AttackIQ/pySigma-backend-kusto#27]
rules laying in sigma under the linux folder has the "none" category and breaks when trying to be converted via the kusto backend.

Routinely getting:
Error while conversion: Unable to determine table name for category: None, category is not yet supported by the pipeline.  Please provide the 'query_table' parameter to the pipeline instead.

Is there planned support for those rules or shall we use 'query_table' for every rule?

**Comment by slincoln-aiq** [comment]
Hey there,

Thanks for bringing this to my attention! I just released v0.4.1, which fixes the error that's raised in your second comment.

As for the the category field, that field is currently used to determine what table to select for the query. I do plan on adding support/mapping out other fields like product & service to tables for each pipeline in the future, but as for now it just relies on the category field or your own supplied query_table parameter.

**Comment by KyootyBella** [comment]
Sounds perfect, I found a loophole where I could just write windows instead in the product which made some of the rules work instantly 😄 
Looking forward to testing your fix!
